title:    Mohanad Salah
url:      "https://moh117.github.io"
#description:
#baseurl: "" # the subpath of your site, e.g. /blog

username: mohdule
author:   Mohanad Salah

# Content settings
excerpt_separator:   <!--excerpt-->
keywords:            [web developer ,web development, web , coding, linux , programmer, python, javascript]

# Build settings
markdown: kramdown
#paginate:
#paginate_path:
gems:     [jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
