title:          Mohanad Salah
#description:
url:            "https://moh117.github.io"
#baseurl: "" # the subpath of your site, e.g. /blog

twitter_username: mohdule
author:           Mohanad Salah
github_username:  mohdule

# Content settings
excerpt_separator:   <!--excerpt-->
keywords:            [web development, web , coding, linux , programming, python, game dev, javascript]

# Build settings
markdown:      kramdown
#paginate:
#paginate_path:
gems:          [jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
