title: MS Blog
name: Mohanad Salah
author: Mohanad Salah

url: http://moh117.github.io
baseurl: ""

markdown: kramdown
highlighter: pygments

excerpt_separator: <!--more-->

keywords:  [web development, web , linux , programming, android, guides]

google_analytics_id: UA-69158926-1

exclude: ["node_modules",
  "gulpfile.js",
  "package.json",
  "README.md"]